"""
Database seeder — populates the database with sample data.
5 users, 15+ listings, 10+ bookings, 20+ reviews, 10 categories.
"""
from datetime import datetime, timedelta
from sqlalchemy.orm import Session
from app.models import User, Listing, Booking, Review, Wishlist, Category


def seed_database(db: Session, force: bool = False):
    """Seed the database with sample data if empty or force is True."""
    # Check if already seeded
    if not force and db.query(User).count() > 0:
        return

    print("[SEED] Seeding database...")

    # ──────────────── Categories ────────────────
    categories = [
        Category(name="Beachfront", icon="🏖️", description="Right on the beach"),
        Category(name="Cabins", icon="🏡", description="Cozy cabins in nature"),
        Category(name="Trending", icon="🔥", description="Popular right now"),
        Category(name="Lakefront", icon="🏞️", description="Lakeside retreats"),
        Category(name="Amazing Pools", icon="🏊", description="Stunning pool properties"),
        Category(name="Countryside", icon="🌾", description="Rural escapes"),
        Category(name="Mansions", icon="🏰", description="Luxurious mansions"),
        Category(name="Tiny Homes", icon="🏠", description="Small and charming"),
        Category(name="Treehouses", icon="🌳", description="Live among the trees"),
        Category(name="Tropical", icon="🌴", description="Tropical paradise"),
        Category(name="Skiing", icon="⛷️", description="Ski-in/ski-out"),
        Category(name="Amazing Views", icon="🏔️", description="Breathtaking views"),
        Category(name="Islands", icon="🏝️", description="Island getaways"),
        Category(name="Camping", icon="⛺", description="Glamping and camping"),
    ]
    db.add_all(categories)
    db.flush()

    # ──────────────── Users ────────────────
    users = [
        User(
            google_id="google_host_001",
            email="sarah.host@gmail.com",
            name="Sarah Johnson",
            avatar_url="https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&crop=face",
            bio="Superhost with 5+ years of experience. I love making guests feel at home!",
            is_host=True,
            is_superhost=True,
        ),
        User(
            google_id="google_host_002",
            email="james.host@gmail.com",
            name="James Wilson",
            avatar_url="https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face",
            bio="Property investor and travel enthusiast. My listings are your perfect getaway.",
            is_host=True,
            is_superhost=False,
        ),
        User(
            google_id="google_host_003",
            email="priya.host@gmail.com",
            name="Priya Sharma",
            avatar_url="https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face",
            bio="Architecture lover and interior designer. Each of my spaces tells a unique story.",
            is_host=True,
            is_superhost=True,
        ),
        User(
            google_id="google_guest_001",
            email="mike.guest@gmail.com",
            name="Mike Chen",
            avatar_url="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
            bio="Digital nomad exploring the world one Airbnb at a time.",
            is_host=False,
        ),
        User(
            google_id="google_guest_002",
            email="emma.guest@gmail.com",
            name="Emma Davis",
            avatar_url="https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face",
            bio="Weekend traveler who loves cozy stays.",
            is_host=False,
        ),
    ]
    db.add_all(users)
    db.flush()

    # ──────────────── Listings ────────────────
    listings = [
        # Sarah's listings (host 1)
        Listing(
            host_id=users[0].id,
            title="Stunning Beachfront Villa with Infinity Pool",
            description="Wake up to the sound of waves in this luxurious beachfront villa. Features a private infinity pool overlooking the ocean, spacious living areas, and a fully equipped gourmet kitchen. Perfect for families or groups seeking an unforgettable beach vacation. The villa is surrounded by tropical gardens and offers direct beach access.\n\nThe space includes a large open-plan living room, a modern kitchen with all amenities, and a beautiful outdoor terrace with ocean views. Each bedroom has its own en-suite bathroom.",
            property_type="Villa",
            category="Beachfront",
            price_per_night=350,
            cleaning_fee=75,
            service_fee=50,
            max_guests=8,
            bedrooms=4,
            beds=5,
            bathrooms=3,
            address="123 Ocean Drive",
            city="Goa",
            state="Goa",
            country="India",
            latitude=15.4909,
            longitude=73.8278,
            amenities=["WiFi", "Pool", "Kitchen", "Air Conditioning", "Beach Access", "Parking", "TV", "Washer", "Dryer", "Hot Tub"],
            images=[
                "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
            ],
            rating_avg=4.92,
            review_count=47,
        ),
        Listing(
            host_id=users[0].id,
            title="Cozy Mountain Cabin with Fireplace",
            description="Escape to this charming mountain cabin nestled among pine trees. Features a wood-burning fireplace, wraparound deck with mountain views, and a fully stocked kitchen. Ideal for couples or small families looking for a peaceful retreat.\n\nThe cabin has been recently renovated with modern amenities while preserving its rustic charm. Enjoy hiking trails right from the doorstep.",
            property_type="Cabin",
            category="Cabins",
            price_per_night=150,
            cleaning_fee=40,
            service_fee=25,
            max_guests=4,
            bedrooms=2,
            beds=2,
            bathrooms=1,
            address="456 Pine Ridge Road",
            city="Manali",
            state="Himachal Pradesh",
            country="India",
            latitude=32.2432,
            longitude=77.1892,
            amenities=["WiFi", "Fireplace", "Kitchen", "Heating", "Parking", "Mountain View", "BBQ Grill", "Hiking"],
            images=[
                "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1518732714860-b62714ce0c59?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1595521624992-48a59aef95e3?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1444201983204-c43cbd584d93?w=800&h=600&fit=crop",
            ],
            rating_avg=4.85,
            review_count=32,
        ),
        Listing(
            host_id=users[0].id,
            title="Modern Luxury Apartment in City Center",
            description="Experience urban living at its finest in this sleek, modern apartment in the heart of the city. Floor-to-ceiling windows offer stunning skyline views. Walking distance to top restaurants, shopping, and nightlife.\n\nThe apartment features high-end finishes, a rain shower, smart home technology, and a state-of-the-art kitchen.",
            property_type="Apartment",
            category="Trending",
            price_per_night=200,
            cleaning_fee=50,
            service_fee=35,
            max_guests=3,
            bedrooms=1,
            beds=1,
            bathrooms=1,
            address="789 MG Road",
            city="Mumbai",
            state="Maharashtra",
            country="India",
            latitude=19.076,
            longitude=72.8777,
            amenities=["WiFi", "Air Conditioning", "Kitchen", "Gym", "Elevator", "TV", "Washer", "City View", "Doorman"],
            images=[
                "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop",
            ],
            rating_avg=4.78,
            review_count=65,
        ),

        # James's listings (host 2)
        Listing(
            host_id=users[1].id,
            title="Lakeside Retreat with Private Dock",
            description="Unwind at this beautiful lakeside property with your own private dock. Enjoy kayaking, fishing, and stunning sunsets over the water. The house features large windows that frame the lake views from every room.\n\nA perfect spot for nature lovers and water sports enthusiasts. The property includes a fire pit area and outdoor dining space.",
            property_type="House",
            category="Lakefront",
            price_per_night=280,
            cleaning_fee=60,
            service_fee=45,
            max_guests=6,
            bedrooms=3,
            beds=4,
            bathrooms=2,
            address="12 Lake View Road",
            city="Udaipur",
            state="Rajasthan",
            country="India",
            latitude=24.5854,
            longitude=73.7125,
            amenities=["WiFi", "Lake View", "Kitchen", "Parking", "Kayaks", "Fire Pit", "BBQ Grill", "Fishing", "Private Dock"],
            images=[
                "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1439130490301-25e322d88054?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&h=600&fit=crop",
            ],
            rating_avg=4.88,
            review_count=28,
        ),
        Listing(
            host_id=users[1].id,
            title="Tropical Paradise Villa with Garden",
            description="Surrounded by lush tropical gardens, this villa offers a serene escape from city life. Features an open-air living area, a beautiful pool, and traditional architecture blended with modern comfort.\n\nEnjoy authentic cuisine at nearby restaurants, explore local markets, and experience the warmth of tropical hospitality.",
            property_type="Villa",
            category="Tropical",
            price_per_night=220,
            cleaning_fee=55,
            service_fee=35,
            max_guests=5,
            bedrooms=2,
            beds=3,
            bathrooms=2,
            address="88 Palm Avenue",
            city="Kerala",
            state="Kerala",
            country="India",
            latitude=10.8505,
            longitude=76.2711,
            amenities=["WiFi", "Pool", "Garden", "Air Conditioning", "Kitchen", "Outdoor Shower", "Yoga Deck", "Parking"],
            images=[
                "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1573052905904-34ad8c27f0cc?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&h=600&fit=crop",
            ],
            rating_avg=4.95,
            review_count=41,
        ),
        Listing(
            host_id=users[1].id,
            title="Designer Tiny Home in the Countryside",
            description="This beautifully designed tiny home proves that small can be extraordinary. Every inch is thoughtfully utilized with custom-built furniture, a cozy loft bed, and a compact but fully functional kitchen.\n\nSurrounded by rolling countryside, it's the perfect digital detox getaway. Sit on the deck and watch the stars at night.",
            property_type="Tiny Home",
            category="Tiny Homes",
            price_per_night=95,
            cleaning_fee=25,
            service_fee=15,
            max_guests=2,
            bedrooms=1,
            beds=1,
            bathrooms=1,
            address="7 Green Valley Lane",
            city="Coorg",
            state="Karnataka",
            country="India",
            latitude=12.3375,
            longitude=75.8069,
            amenities=["WiFi", "Kitchen", "Parking", "Garden View", "Heating", "Coffee Maker", "Books", "Stargazing Deck"],
            images=[
                "https://images.unsplash.com/photo-1558036117-15d82a90b9b1?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1523217582562-09d0def993a6?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1510627489930-0c1b0bfb6785?w=800&h=600&fit=crop",
            ],
            rating_avg=4.90,
            review_count=55,
        ),
        Listing(
            host_id=users[1].id,
            title="Penthouse Suite with Panoramic City Views",
            description="Live like royalty in this stunning penthouse occupying the entire top floor. 360-degree city views, a private rooftop terrace, and luxurious interiors make this the ultimate urban retreat.\n\nPerfect for special occasions or when you want to treat yourself to something extraordinary.",
            property_type="Apartment",
            category="Mansions",
            price_per_night=500,
            cleaning_fee=100,
            service_fee=75,
            max_guests=4,
            bedrooms=2,
            beds=2,
            bathrooms=2.5,
            address="1 Sky Tower, Bandra",
            city="Mumbai",
            state="Maharashtra",
            country="India",
            latitude=19.0596,
            longitude=72.8295,
            amenities=["WiFi", "Air Conditioning", "Kitchen", "Rooftop Terrace", "Gym", "Concierge", "City View", "Wine Cellar", "Home Theater"],
            images=[
                "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1600566753376-12c8ab7c5a38?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop",
            ],
            rating_avg=4.97,
            review_count=19,
        ),

        # Priya's listings (host 3)
        Listing(
            host_id=users[2].id,
            title="Heritage Haveli with Courtyard",
            description="Step back in time in this beautifully restored heritage haveli. Original frescoes, carved sandstone pillars, and a peaceful inner courtyard create an atmosphere of timeless elegance.\n\nModern amenities blend seamlessly with historical architecture. The rooftop terrace offers views of the old city.",
            property_type="House",
            category="Trending",
            price_per_night=175,
            cleaning_fee=45,
            service_fee=30,
            max_guests=6,
            bedrooms=3,
            beds=3,
            bathrooms=2,
            address="42 Old City Road",
            city="Jaipur",
            state="Rajasthan",
            country="India",
            latitude=26.9124,
            longitude=75.7873,
            amenities=["WiFi", "Air Conditioning", "Courtyard", "Rooftop Terrace", "Kitchen", "City View", "Cultural Experience", "Parking"],
            images=[
                "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&h=600&fit=crop",
            ],
            rating_avg=4.82,
            review_count=37,
        ),
        Listing(
            host_id=users[2].id,
            title="Treehouse Escape in the Forest",
            description="Experience childhood dreams come true in this magical treehouse perched high among ancient trees. Connected by wooden walkways and surrounded by birdsong, it's a truly unique stay.\n\nThe treehouse is surprisingly spacious with a comfortable queen bed, a small kitchen, and a balcony perfect for morning coffee.",
            property_type="Treehouse",
            category="Treehouses",
            price_per_night=180,
            cleaning_fee=35,
            service_fee=30,
            max_guests=2,
            bedrooms=1,
            beds=1,
            bathrooms=1,
            address="Forest Reserve Area",
            city="Wayanad",
            state="Kerala",
            country="India",
            latitude=11.6854,
            longitude=76.1320,
            amenities=["WiFi", "Kitchen", "Nature View", "Bird Watching", "Breakfast Included", "Eco-friendly", "Hiking Trails"],
            images=[
                "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1601918774946-25832a4be0d6?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1534067783941-51c9c23ecefd?w=800&h=600&fit=crop",
            ],
            rating_avg=4.93,
            review_count=24,
        ),
        Listing(
            host_id=users[2].id,
            title="Luxurious Pool Villa with Mountain Views",
            description="Indulge in luxury at this magnificent villa featuring a stunning infinity pool with mountain views. The villa boasts spacious bedrooms, a gourmet kitchen, and elegant outdoor dining areas.\n\nPerfect for celebrations, retreats, or simply a lavish getaway. Personal chef and spa services available upon request.",
            property_type="Villa",
            category="Amazing Pools",
            price_per_night=420,
            cleaning_fee=80,
            service_fee=65,
            max_guests=10,
            bedrooms=5,
            beds=6,
            bathrooms=4,
            address="99 Hilltop Road",
            city="Lonavala",
            state="Maharashtra",
            country="India",
            latitude=18.7546,
            longitude=73.4062,
            amenities=["WiFi", "Infinity Pool", "Kitchen", "Air Conditioning", "Mountain View", "Parking", "BBQ Grill", "Home Theater", "Spa", "Gym"],
            images=[
                "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&h=600&fit=crop",
            ],
            rating_avg=4.96,
            review_count=33,
        ),
        Listing(
            host_id=users[2].id,
            title="Charming Studio in Artsy Neighborhood",
            description="A bright and cheerful studio apartment in the heart of the city's art district. Surrounded by galleries, cafes, and street art. The space is decorated with local artwork and has a bohemian vibe.\n\nGreat for solo travelers or couples who want to experience the creative side of the city.",
            property_type="Apartment",
            category="Trending",
            price_per_night=85,
            cleaning_fee=20,
            service_fee=15,
            max_guests=2,
            bedrooms=1,
            beds=1,
            bathrooms=1,
            address="33 Art Lane, Hauz Khas",
            city="Delhi",
            state="Delhi",
            country="India",
            latitude=28.5494,
            longitude=77.2001,
            amenities=["WiFi", "Air Conditioning", "Kitchen", "TV", "Washer", "Art Supplies", "Books", "Coffee Maker"],
            images=[
                "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800&h=600&fit=crop",
            ],
            rating_avg=4.75,
            review_count=58,
        ),
        Listing(
            host_id=users[0].id,
            title="Seaside Cottage with Private Garden",
            description="A quaint seaside cottage with a charming private garden just steps from the beach. Whitewashed walls, blue shutters, and a cozy interior create a picture-perfect coastal retreat.\n\nEnjoy fresh seafood at nearby shacks, watch dolphins from the shore, and fall asleep to the sound of waves.",
            property_type="Cottage",
            category="Beachfront",
            price_per_night=130,
            cleaning_fee=30,
            service_fee=20,
            max_guests=4,
            bedrooms=2,
            beds=2,
            bathrooms=1,
            address="5 Coastal Path",
            city="Pondicherry",
            state="Puducherry",
            country="India",
            latitude=11.9416,
            longitude=79.8083,
            amenities=["WiFi", "Garden", "Beach Access", "Kitchen", "Parking", "Outdoor Dining", "Hammock", "Pet Friendly"],
            images=[
                "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1475855581690-80accde3ae2b?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=800&h=600&fit=crop",
            ],
            rating_avg=4.87,
            review_count=42,
        ),
        Listing(
            host_id=users[1].id,
            title="Ski Chalet with Hot Tub & Mountain Access",
            description="Hit the slopes from this stunning ski chalet with direct mountain access. After a day of skiing, relax in the private outdoor hot tub with panoramic mountain views.\n\nThe chalet features a stone fireplace, ski storage, boot warmers, and a fully stocked bar. Ski rental and lessons available nearby.",
            property_type="Chalet",
            category="Skiing",
            price_per_night=310,
            cleaning_fee=70,
            service_fee=50,
            max_guests=8,
            bedrooms=4,
            beds=5,
            bathrooms=3,
            address="15 Snow Peak Road",
            city="Gulmarg",
            state="Jammu and Kashmir",
            country="India",
            latitude=34.0484,
            longitude=74.3805,
            amenities=["WiFi", "Hot Tub", "Fireplace", "Kitchen", "Ski-in/Ski-out", "Heating", "Mountain View", "Parking", "Boot Warmers", "Bar"],
            images=[
                "https://images.unsplash.com/photo-1518732714860-b62714ce0c59?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1444201983204-c43cbd584d93?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop",
            ],
            rating_avg=4.91,
            review_count=22,
        ),
        Listing(
            host_id=users[2].id,
            title="Island Bungalow with Crystal Clear Waters",
            description="Your private island paradise awaits. This overwater-style bungalow sits right on the shoreline with crystal clear waters just steps away. Snorkel right from your deck!\n\nFeatures include a glass floor panel to watch marine life, an outdoor rain shower, and a hammock over the water.",
            property_type="Bungalow",
            category="Islands",
            price_per_night=275,
            cleaning_fee=55,
            service_fee=45,
            max_guests=2,
            bedrooms=1,
            beds=1,
            bathrooms=1,
            address="Island Resort Road",
            city="Andaman",
            state="Andaman and Nicobar",
            country="India",
            latitude=11.7401,
            longitude=92.6586,
            amenities=["WiFi", "Ocean View", "Snorkeling Gear", "Outdoor Shower", "Hammock", "Breakfast Included", "Glass Floor", "Kayak"],
            images=[
                "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1573052905904-34ad8c27f0cc?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop",
            ],
            rating_avg=4.94,
            review_count=18,
        ),
        Listing(
            host_id=users[0].id,
            title="Glamping Dome Under the Stars",
            description="Experience the great outdoors in style with this transparent glamping dome. Fall asleep watching the stars and wake up to sunrise over the valley. All the comfort of a hotel room, none of the walls.\n\nIncludes a comfortable king bed, solar-powered lights, a portable heater, and a private outdoor fire pit area.",
            property_type="Dome",
            category="Camping",
            price_per_night=120,
            cleaning_fee=25,
            service_fee=20,
            max_guests=2,
            bedrooms=1,
            beds=1,
            bathrooms=1,
            address="Eco Farm, Valley Road",
            city="Munnar",
            state="Kerala",
            country="India",
            latitude=10.0889,
            longitude=77.0595,
            amenities=["Stargazing", "Fire Pit", "Breakfast Included", "Eco-friendly", "Valley View", "Hiking", "Tea Plantation Tours"],
            images=[
                "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1534067783941-51c9c23ecefd?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1601918774946-25832a4be0d6?w=800&h=600&fit=crop",
                "https://images.unsplash.com/photo-1510627489930-0c1b0bfb6785?w=800&h=600&fit=crop",
            ],
            rating_avg=4.89,
            review_count=31,
        ),
    ]
    db.add_all(listings)
    db.flush()

    # ──────────────── Bookings ────────────────
    today = datetime.now().date()
    bookings = [
        # Past completed bookings
        Booking(listing_id=listings[0].id, guest_id=users[3].id,
                check_in=(today - timedelta(days=30)).isoformat(), check_out=(today - timedelta(days=25)).isoformat(),
                guests=4, total_price=1875, status="completed"),
        Booking(listing_id=listings[1].id, guest_id=users[4].id,
                check_in=(today - timedelta(days=20)).isoformat(), check_out=(today - timedelta(days=17)).isoformat(),
                guests=2, total_price=515, status="completed"),
        Booking(listing_id=listings[4].id, guest_id=users[3].id,
                check_in=(today - timedelta(days=15)).isoformat(), check_out=(today - timedelta(days=12)).isoformat(),
                guests=3, total_price=750, status="completed"),
        Booking(listing_id=listings[7].id, guest_id=users[4].id,
                check_in=(today - timedelta(days=40)).isoformat(), check_out=(today - timedelta(days=36)).isoformat(),
                guests=4, total_price=775, status="completed"),
        Booking(listing_id=listings[2].id, guest_id=users[3].id,
                check_in=(today - timedelta(days=10)).isoformat(), check_out=(today - timedelta(days=7)).isoformat(),
                guests=2, total_price=685, status="completed"),
        # Upcoming confirmed bookings
        Booking(listing_id=listings[0].id, guest_id=users[4].id,
                check_in=(today + timedelta(days=5)).isoformat(), check_out=(today + timedelta(days=10)).isoformat(),
                guests=6, total_price=1875, status="confirmed"),
        Booking(listing_id=listings[3].id, guest_id=users[3].id,
                check_in=(today + timedelta(days=7)).isoformat(), check_out=(today + timedelta(days=12)).isoformat(),
                guests=4, total_price=1505, status="confirmed"),
        Booking(listing_id=listings[9].id, guest_id=users[4].id,
                check_in=(today + timedelta(days=14)).isoformat(), check_out=(today + timedelta(days=18)).isoformat(),
                guests=8, total_price=1825, status="confirmed"),
        # Cancelled booking
        Booking(listing_id=listings[5].id, guest_id=users[3].id,
                check_in=(today + timedelta(days=3)).isoformat(), check_out=(today + timedelta(days=6)).isoformat(),
                guests=2, total_price=325, status="cancelled"),
        Booking(listing_id=listings[10].id, guest_id=users[3].id,
                check_in=(today + timedelta(days=20)).isoformat(), check_out=(today + timedelta(days=24)).isoformat(),
                guests=2, total_price=600, status="confirmed"),
        Booking(listing_id=listings[6].id, guest_id=users[4].id,
                check_in=(today + timedelta(days=30)).isoformat(), check_out=(today + timedelta(days=33)).isoformat(),
                guests=3, total_price=1675, status="confirmed"),
    ]
    db.add_all(bookings)
    db.flush()

    # ──────────────── Reviews ────────────────
    reviews = [
        Review(listing_id=listings[0].id, user_id=users[3].id, booking_id=bookings[0].id,
               rating=5, comment="Absolutely stunning villa! The infinity pool with ocean views was a dream. Sarah was an amazing host — she left a welcome basket with local treats. Can't wait to come back!"),
        Review(listing_id=listings[1].id, user_id=users[4].id, booking_id=bookings[1].id,
               rating=5, comment="The coziest cabin I've ever stayed in. The fireplace made cold evenings magical. Woke up to beautiful mountain views every morning. Highly recommend!"),
        Review(listing_id=listings[4].id, user_id=users[3].id, booking_id=bookings[2].id,
               rating=5, comment="Paradise on earth! The tropical garden was gorgeous, and the pool was perfect. James was very responsive and even arranged a local cooking class for us."),
        Review(listing_id=listings[7].id, user_id=users[4].id, booking_id=bookings[3].id,
               rating=4, comment="The heritage haveli was beautiful and full of character. The rooftop views of Jaipur were incredible. Only wish the WiFi was a bit stronger, but that's a minor complaint."),
        Review(listing_id=listings[2].id, user_id=users[3].id, booking_id=bookings[4].id,
               rating=5, comment="Modern, clean, and perfectly located. Walking distance to everything. The city views from the apartment were stunning, especially at night. Will definitely book again!"),
        # Additional reviews without booking IDs (for variety)
        Review(listing_id=listings[0].id, user_id=users[4].id,
               rating=5, comment="We celebrated our anniversary here and it was perfect. The villa is even more beautiful than the photos. Beach access was a huge plus!"),
        Review(listing_id=listings[3].id, user_id=users[3].id,
               rating=5, comment="The lakeside views were mesmerizing. We spent our days kayaking and evenings by the fire pit. Such a peaceful and rejuvenating experience."),
        Review(listing_id=listings[5].id, user_id=users[4].id,
               rating=5, comment="The tiny home was adorable and so well-designed! Every little detail was thoughtful. The countryside setting was incredibly peaceful. Perfect for a weekend escape."),
        Review(listing_id=listings[6].id, user_id=users[3].id,
               rating=5, comment="Unbelievable penthouse! The panoramic views from the rooftop terrace took our breath away. Everything was top-notch quality. Worth every penny!"),
        Review(listing_id=listings[8].id, user_id=users[4].id,
               rating=5, comment="A dream come true! Sleeping in a treehouse surrounded by birds chirping was magical. The breakfast was delicious and the trails were amazing."),
        Review(listing_id=listings[9].id, user_id=users[3].id,
               rating=5, comment="The infinity pool with mountain views was jaw-dropping. This villa is perfect for a group celebration. The home theater was a fantastic bonus on rainy days."),
        Review(listing_id=listings[10].id, user_id=users[4].id,
               rating=4, comment="Such a creative and cozy studio! The artsy neighborhood was full of interesting cafes and galleries. Great for a solo creative retreat."),
        Review(listing_id=listings[11].id, user_id=users[3].id,
               rating=5, comment="The seaside cottage was pure charm. The private garden with a hammock was my favorite spot. Fresh seafood from the nearby shacks was incredible."),
        Review(listing_id=listings[12].id, user_id=users[4].id,
               rating=5, comment="Skiing right from the doorstep! And the hot tub after a long day on the slopes was heavenly. The chalet was warm, well-equipped, and beautifully decorated."),
        Review(listing_id=listings[13].id, user_id=users[3].id,
               rating=5, comment="The overwater bungalow was out of this world! Watching fish through the glass floor panel was so cool. The snorkeling right from our deck was unbeatable."),
        Review(listing_id=listings[14].id, user_id=users[4].id,
               rating=5, comment="Falling asleep under the stars in the glamping dome was a once-in-a-lifetime experience. The valley views at sunrise were breathtaking. Truly unique!"),
        Review(listing_id=listings[0].id, user_id=users[3].id,
               rating=4, comment="Great villa overall. The pool was amazing and the beach was beautiful. The only reason I'm not giving 5 stars is that it took a bit long to get there from the airport."),
        Review(listing_id=listings[2].id, user_id=users[4].id,
               rating=5, comment="Best apartment I've stayed in! The smart home features were impressive, and the location couldn't be more convenient. Clean, stylish, and comfortable."),
        Review(listing_id=listings[4].id, user_id=users[4].id,
               rating=5, comment="The yoga deck overlooking the pool was my happy place. The tropical gardens were beautifully maintained. A truly serene and special place."),
        Review(listing_id=listings[9].id, user_id=users[4].id,
               rating=5, comment="We had our family reunion at this villa and it was spectacular. Enough space for everyone, the pool was a hit with the kids, and the mountain views were gorgeous."),
    ]
    db.add_all(reviews)
    db.flush()

    # ──────────────── Wishlists ────────────────
    wishlists = [
        Wishlist(user_id=users[3].id, listing_id=listings[0].id),
        Wishlist(user_id=users[3].id, listing_id=listings[4].id),
        Wishlist(user_id=users[3].id, listing_id=listings[8].id),
        Wishlist(user_id=users[3].id, listing_id=listings[13].id),
        Wishlist(user_id=users[4].id, listing_id=listings[1].id),
        Wishlist(user_id=users[4].id, listing_id=listings[6].id),
        Wishlist(user_id=users[4].id, listing_id=listings[9].id),
        Wishlist(user_id=users[4].id, listing_id=listings[14].id),
    ]
    db.add_all(wishlists)

    db.commit()
    print("[OK] Database seeded successfully!")
    print(f"   - {len(users)} users")
    print(f"   - {len(listings)} listings")
    print(f"   - {len(bookings)} bookings")
    print(f"   - {len(reviews)} reviews")
    print(f"   - {len(wishlists)} wishlists")
    print(f"   - {len(categories)} categories")


def reset_database(db: Session):
    """Wipe all existing records and re-seed clean demo data."""
    print("[SEED] Resetting database records...")
    db.query(Wishlist).delete()
    db.query(Review).delete()
    db.query(Booking).delete()
    db.query(Listing).delete()
    db.query(Category).delete()
    db.query(User).delete()
    db.commit()
    seed_database(db, force=True)
